import { ControllerAdmin } from '@lionrockjs/mod-admin';
export default class ControllerAdminPage extends ControllerAdmin {
    static STATE_ORIGINAL_SNAPSHOT: string;
    static STATE_POST_ORIGINAL: string;
    page_type: string;
    controller_slug: string;
    constructor(request: any, options?: {});
    action_index(): Promise<void>;
    action_create_by_type(): Promise<void>;
    action_import_post(): Promise<void>;
    action_search(): Promise<void>;
    publish_weights(): Promise<void>;
    action_new_post(): Promise<void>;
    isPostOriginalDiff(postOriginal: any, original: any, action: any): boolean;
    saveVersion(postOriginal: any, original: any, id: any, slug: any, action: any): Promise<void>;
    action_update(): Promise<void>;
    updateLiveSchedule(instance: any): Promise<void>;
    unpublish(id: any): Promise<void>;
    revert(page: any): Promise<void>;
    publish(page: any): Promise<void>;
    action_unpublish(): Promise<void>;
    setEditTemplate(page: any, livePage?: any, placeholders?: {}, tags?: {}): void;
    action_create(): Promise<void>;
    static traverse(obj: any, parentKey?: string, callback?: () => void): void;
    static hasPointer(obj: any): boolean;
    static resolvePointer(state: any, original: any): Promise<void>;
    action_edit(): Promise<void>;
    action_read(): Promise<void>;
    action_trash_list(): Promise<void>;
    action_restore(): Promise<void>;
    action_delete(): Promise<void>;
    action_add_item(): Promise<void>;
    action_delete_item(): Promise<void>;
    block_add(page: any, blockName: any): Promise<void>;
    block_delete(page: any, blockIndex: any): Promise<void>;
    block_item_add(page: any, blockIndex: any, itemName: any, count?: number): Promise<void>;
    block_item_delete(page: any, blockIndex: any, itemName: any, itemIndex: any): Promise<void>;
    item_add(page: any, itemName: any, count?: number): Promise<void>;
    item_delete(page: any, itemName: any, itemIndex: any): Promise<void>;
    action_add_block(): Promise<void>;
    action_delete_block(): Promise<void>;
    action_add_block_item(): Promise<void>;
    action_delete_block_item(): Promise<void>;
}
